In [36]:
import numpy as np

In [40]:
arr = np.array([1,2,3,4])

In [41]:
arr

array([1, 2, 3, 4])

In [8]:
my_arry = np.arange(1000)

In [26]:
data = np.random.rand(2, 5, 3, 1)

In [27]:
data


array([[[[0.78476328],
         [0.70098838],
         [0.27869455]],

        [[0.41478898],
         [0.81296229],
         [0.40430977]],

        [[0.94407287],
         [0.67367582],
         [0.07730522]],

        [[0.85560049],
         [0.55638585],
         [0.08098786]],

        [[0.09927429],
         [0.48862855],
         [0.53709165]]],


       [[[0.69889195],
         [0.58016941],
         [0.98593842]],

        [[0.4670827 ],
         [0.37970287],
         [0.16799459]],

        [[0.38736204],
         [0.23319137],
         [0.30366151]],

        [[0.05951729],
         [0.40971289],
         [0.03371935]],

        [[0.58500846],
         [0.30151061],
         [0.06996142]]]])

In [24]:
# rand = only positive
# randn = both negative and positive
# randint = for giving range

In [25]:
data.shape

(2, 5)

In [48]:
arry2 = np.arange(120)

In [49]:
print(arry2)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]


In [50]:
arry2.shape

(120,)

In [53]:
arry2.reshape(2,10,6)

array([[[  0,   1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10,  11],
        [ 12,  13,  14,  15,  16,  17],
        [ 18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40,  41],
        [ 42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53],
        [ 54,  55,  56,  57,  58,  59]],

       [[ 60,  61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77],
        [ 78,  79,  80,  81,  82,  83],
        [ 84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101],
        [102, 103, 104, 105, 106, 107],
        [108, 109, 110, 111, 112, 113],
        [114, 115, 116, 117, 118, 119]]])

In [55]:
d = np.zeros(2)

In [56]:
d

array([0., 0.])

In [57]:
da = np.empty(10)

In [58]:
da

array([0.57983204, 0.71116894, 0.61126663, 0.08802069, 0.8031109 ,
       0.71498443, 0.84892941, 0.4293415 , 0.70960597, 0.55044722])

In [59]:
arr = np.array([1,2,3]), dtype = int8

SyntaxError: cannot assign to function call (<ipython-input-59-515162dce381>, line 1)