In [1]:
import numpy as np

Boolian Indexing

In [2]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [3]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [4]:
data[names == 'Bob']

array([[-0.32346514,  2.05123243,  0.50934104, -1.14479651],
       [-0.4638774 ,  0.22627726, -0.65030481, -0.48203712]])

In [9]:
data[names == 'Bob',0:2]

array([[-0.32346514,  2.05123243],
       [-0.4638774 ,  0.22627726]])

In [11]:
data[data < 0]

array([-0.32346514, -1.14479651, -2.25729002, -0.19205747, -0.32437719,
       -0.93559478, -0.4638774 , -0.65030481, -0.48203712, -0.51753854,
       -1.49372862, -1.48224419, -0.70063277, -2.0486223 , -0.80290722,
       -0.85080758, -1.13940079])

Fancy Indexing

In [12]:
arr = np.arange(32).reshape((8, 4))

In [13]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [22]:
arr[[0,2,4,6]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19],
       [24, 25, 26, 27]])

In [19]:
arr[[0,2,4,6],0]

array([ 0,  8, 16, 24])

In [21]:
t_arr = arr[[0,2,4,6]]

In [30]:
np.array([t_arr[:,0], t_arr[:,2]])

array([[ 0,  8, 16, 24],
       [ 2, 10, 18, 26]])

Transposing Arrays and Swapping Axes


In [32]:
t_arr.T

array([[ 0,  8, 16, 24],
       [ 1,  9, 17, 25],
       [ 2, 10, 18, 26],
       [ 3, 11, 19, 27]])

In [34]:
np.dot(arr,t_arr)

array([[ 112,  118,  124,  130],
       [ 304,  326,  348,  370],
       [ 496,  534,  572,  610],
       [ 688,  742,  796,  850],
       [ 880,  950, 1020, 1090],
       [1072, 1158, 1244, 1330],
       [1264, 1366, 1468, 1570],
       [1456, 1574, 1692, 1810]])

In [35]:
arr = np.arange(16).reshape((2, 2, 4))

In [36]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [37]:
arr.transpose((1, 0, 2))


array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [ ]:
# 0 = rows
# 1 = colum
# 2 = depth

In [40]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [41]:
arr.T

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

Universal Functions: Fast Element-Wise Array
Functions

In [44]:
arr = np.arange(10)

In [45]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [47]:
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [48]:
x = np.random.randn(8)
y = np.random.randn(8)

In [49]:
x,y

(array([ 0.11724984,  0.990221  ,  0.23200501,  1.17928867,  0.59790394,
         0.84108475,  0.00488695, -0.3014301 ]),
 array([ 0.65519519,  0.4193201 , -0.45636689,  0.64554146, -0.61903841,
         1.07138019, -0.36211815, -0.04058377]))

In [50]:
np.maximum(x,y)

array([ 0.65519519,  0.990221  ,  0.23200501,  1.17928867,  0.59790394,
        1.07138019,  0.00488695, -0.04058377])

In [51]:
np.minimum(x,y)

array([ 0.11724984,  0.4193201 , -0.45636689,  0.64554146, -0.61903841,
        0.84108475, -0.36211815, -0.3014301 ])

In [53]:
remainder, whole_part = np.modf(arr)

In [54]:
remainder

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [55]:
whole_part

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [56]:
arr.sort()

In [57]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Unique and Other Set Logic


In [65]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [59]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [62]:
names1 = np.array(['Bob', 'Joe'])

In [63]:
np.intersect1d(names,names1)

array(['Bob', 'Joe'], dtype='<U3')

In [66]:
np.union1d(names,names1)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [68]:
np.in1d(names,names1)

array([ True,  True, False,  True, False,  True,  True])