In [1]:
import numpy as np

In [81]:
arrays = np.array([[1,0,3],[4,5,6]])

In [49]:
arry

array([[11, 12, 13],
       [14, 15, 16]], dtype=int8)

In [50]:
arry.dtype

dtype('int8')

In [51]:
#arry = arry.astype('int8')

In [52]:
arry.dtype

dtype('int8')

In [53]:
ar = arry + arry

In [54]:
ar

array([[22, 24, 26],
       [28, 30, 32]], dtype=int8)

In [55]:
array = array + 5

In [57]:
array

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [85]:
arr2ds = np.arange(6).reshape(2,3).astype('int32')

In [88]:
arr2ds

array([[0, 1, 2],
       [3, 4, 5]])

In [87]:
arrays > arr2d

array([[ True, False,  True],
       [ True,  True,  True]])

In [83]:
arrays < arr2ds

array([[False,  True, False],
       [False, False, False]])

In [86]:
arrays == arr2d

array([[False, False, False],
       [False, False, False]])

In [89]:
arr = np.arange(10)

In [90]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
arr[4:6]

array([4, 5])

In [105]:
arr[0] = 0

In [106]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [129]:
arr1 = arr[:].copy()

In [127]:
arr_sl[4] = 5

In [122]:
arr_s

array([1, 2, 3, 4, 1])

In [123]:
arr

array([0, 1, 2, 3, 4, 1, 6, 7, 8, 9])

In [128]:
arr_sl

array([1, 2, 3, 4, 5])

In [130]:
arr1[:] = 0

In [131]:
arr1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [137]:
arry1 = np.arange(20).reshape(4,5)

In [138]:
arry1


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [154]:
arry1[0][2:4]

array([2, 3])

In [160]:
arry1[0:2, 2:4]

array([[2, 3],
       [7, 8]])

In [139]:
arry3d = np.arange(45).reshape(3,3,5)

In [140]:
arry3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]]])

In [161]:
array3d = np.array([[[0,1,2,3],[4,5,6,7]],[[8,9,10,11],[12,13,14,15]]])

In [162]:
array3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [164]:
array2d = np.arange(10).reshape(2,5)

In [165]:
array2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [170]:
array2d[::-1]

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])